### ISSUE TITLE
Image rendering fails in the function check_visibility()

### ISSUE THREAD

**Issue by basitanees** [facebookresearch/clevr-dataset-gen#27]
Hi, I am trying to generate images however, it fails with the following output in the check_visibility() function in render_images.py. Any help is appreciated.

Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Koc\CLEVR_v1.0_no_images\clevr-dataset-gen\image_generation\render_images.py", line 568, in <module>
    main(args)
  File "C:\Koc\CLEVR_v1.0_no_images\clevr-dataset-gen\image_generation\render_images.py", line 187, in main
    output_blendfile=blend_path,
  File "C:\Koc\CLEVR_v1.0_no_images\clevr-dataset-gen\image_generation\render_images.py", line 310, in render_scene
    objects, blender_objects = add_random_objects(scene_struct, num_objects, args, camera)
  File "C:\Koc\CLEVR_v1.0_no_images\clevr-dataset-gen\image_generation\render_images.py", line 368, in add_random_objects
    return add_random_objects(scene_struct, num_objects, args, camera)
  File "C:\Koc\CLEVR_v1.0_no_images\clevr-dataset-gen\image_generation\render_images.py", line 368, in add_random_objects
    return add_random_objects(scene_struct, num_objects, args, camera)
  File "C:\Koc\CLEVR_v1.0_no_images\clevr-dataset-gen\image_generation\render_images.py", line 368, in add_random_objects
    return add_random_objects(scene_struct, num_objects, args, camera)
  File "C:\Koc\CLEVR_v1.0_no_images\clevr-dataset-gen\image_generation\render_images.py", line 436, in add_random_objects
    all_visible = check_visibility(blender_objects, args.min_pixels_per_object)
  File "C:\Koc\CLEVR_v1.0_no_images\clevr-dataset-gen\image_generation\render_images.py", line 492, in check_visibility
    os.remove(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\basit\\AppData\\Local\\Temp\\tmpmxvc4f2e.png'

Blender quit

#####################################################################

This is my full output after running the command "blender --background --python render_images.py -- --num_images 10"

AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
found bundled python: C:\Program Files\Blender Foundation\Blender\2.78\python
read blend: data/base_scene.blend
convertViewVec: called in an invalid context
convertViewVec: called in an invalid context
convertViewVec: called in an invalid context
0.08877431084461573 0.4 front
BROKEN MARGIN!
0.04820750292907583 0.4 behind
BROKEN MARGIN!
convertViewVec: called in an invalid context
convertViewVec: called in an invalid context
0.19977840115083056 0.4 right
BROKEN MARGIN!
0.08536601609309091 0.4 left
BROKEN MARGIN!
0.2000458868872319 0.4 behind
BROKEN MARGIN!
0.0873495889211191 0.4 front
BROKEN MARGIN!
0.29951943072529086 0.4 behind
BROKEN MARGIN!
0.21364749111962933 0.4 front
BROKEN MARGIN!
0.2549460895803004 0.4 left
BROKEN MARGIN!
0.003022989710967261 0.4 behind
BROKEN MARGIN!
0.15800284141277743 0.4 behind
BROKEN MARGIN!
0.07528758013917058 0.4 left
BROKEN MARGIN!
0.3628168400865366 0.4 behind
BROKEN MARGIN!
0.2012267348291028 0.4 left
BROKEN MARGIN!
0.018027017109982335 0.4 front
BROKEN MARGIN!
0.36046965269699305 0.4 front
BROKEN MARGIN!
0.27587637276083776 0.4 front
BROKEN MARGIN!
convertViewVec: called in an invalid context
0.2611278506012926 0.4 front
BROKEN MARGIN!
0.17951250110849548 0.4 front
BROKEN MARGIN!
0.38857280951171447 0.4 front
BROKEN MARGIN!
0.18484803662545168 0.4 right
BROKEN MARGIN!
0.1934248473197031 0.4 front
BROKEN MARGIN!
0.061180339553252416 0.4 front
BROKEN MARGIN!
0.32210705874923606 0.4 right
BROKEN MARGIN!
0.025174628800542997 0.4 front
BROKEN MARGIN!
0.3039664182996975 0.4 behind
BROKEN MARGIN!
0.3932510033371407 0.4 behind
BROKEN MARGIN!
0.1878642509881865 0.4 behind
BROKEN MARGIN!
0.3168021906515279 0.4 left
BROKEN MARGIN!
0.12667748818839542 0.4 front
BROKEN MARGIN!
0.2549021012303956 0.4 behind
BROKEN MARGIN!
0.17429347558240815 0.4 front
BROKEN MARGIN!
0.2816311804500198 0.4 front
BROKEN MARGIN!
0.3416351283617378 0.4 right
BROKEN MARGIN!
0.1585543098115758 0.4 right
BROKEN MARGIN!
0.03309468716003261 0.4 front
BROKEN MARGIN!
convertViewVec: called in an invalid context
convertViewVec: called in an invalid context
convertViewVec: called in an invalid context
convertViewVec: called in an invalid context
convertViewVec: called in an invalid context
0.31520377161982727 0.4 front
BROKEN MARGIN!
0.036695282914279925 0.4 right
BROKEN MARGIN!
0.27263846978608974 0.4 behind
BROKEN MARGIN!
0.2627497052155988 0.4 front
BROKEN MARGIN!
convertViewVec: called in an invalid context
convertViewVec: called in an invalid context
0.23823929156837098 0.4 front
BROKEN MARGIN!
0.20292554043543543 0.4 right
BROKEN MARGIN!
0.05131734885347661 0.4 behind
BROKEN MARGIN!
0.11015337088431831 0.4 left
BROKEN MARGIN!
0.3012921639788525 0.4 behind
BROKEN MARGIN!
0.196631895470063 0.4 left
BROKEN MARGIN!
0.14357856465165075 0.4 behind
BROKEN MARGIN!
0.17079742580825474 0.4 left
BROKEN MARGIN!
0.2133834050769048 0.4 right
BROKEN MARGIN!
0.027611544870251636 0.4 front
BROKEN MARGIN!
0.3380986087170943 0.4 left
BROKEN MARGIN!
0.12554075248581043 0.4 behind
BROKEN MARGIN!
0.2644719437791302 0.4 left
BROKEN MARGIN!
0.22837131874101524 0.4 right
BROKEN MARGIN!
0.27992444075169554 0.4 behind
BROKEN MARGIN!
0.1121455771594837 0.4 front
BROKEN MARGIN!
0.2609541712115029 0.4 front
BROKEN MARGIN!
0.009093892328399189 0.4 behind
BROKEN MARGIN!
0.22688637130491607 0.4 right
BROKEN MARGIN!
0.25159153734433315 0.4 left
BROKEN MARGIN!
convertViewVec: called in an invalid context
convertViewVec: called in an invalid context
convertViewVec: called in an invalid context
convertViewVec: called in an invalid context
0.16587828357933465 0.4 behind
BROKEN MARGIN!
0.23942782585801536 0.4 behind
BROKEN MARGIN!
convertViewVec: called in an invalid context
convertViewVec: called in an invalid context
0.15818168059642357 0.4 right
BROKEN MARGIN!
0.32174770794017993 0.4 left
BROKEN MARGIN!
0.04934954263118774 0.4 left
BROKEN MARGIN!
0.04872374480676189 0.4 behind
BROKEN MARGIN!
0.07912650115289654 0.4 behind
BROKEN MARGIN!
0.36737731821024266 0.4 behind
BROKEN MARGIN!
convertViewVec: called in an invalid context
convertViewVec: called in an invalid context
0.23321592503030142 0.4 front
BROKEN MARGIN!
0.33803206920973494 0.4 behind
BROKEN MARGIN!
0.23251556811053053 0.4 behind
BROKEN MARGIN!
0.026286593130376845 0.4 right
BROKEN MARGIN!
0.37975706958135635 0.4 front
BROKEN MARGIN!
0.09096281901894843 0.4 behind
BROKEN MARGIN!
0.06642285983956242 0.4 left
BROKEN MARGIN!
0.14779452715317143 0.4 left
BROKEN MARGIN!
0.14547698733790737 0.4 front
BROKEN MARGIN!
0.05800929115355369 0.4 behind
BROKEN MARGIN!
0.2935328323114679 0.4 front
BROKEN MARGIN!
0.04034805536422903 0.4 left
BROKEN MARGIN!
0.23227894436989893 0.4 behind
BROKEN MARGIN!
0.2730608451646215 0.4 behind
BROKEN MARGIN!
0.12994023643916175 0.4 left
BROKEN MARGIN!
0.38239603391839716 0.4 front
BROKEN MARGIN!
0.020917860854106962 0.4 behind
BROKEN MARGIN!
0.11173843114846238 0.4 behind
BROKEN MARGIN!
0.15806884052201386 0.4 front
BROKEN MARGIN!
0.19924301764122276 0.4 behind
BROKEN MARGIN!
0.25774415927266725 0.4 right
BROKEN MARGIN!
0.14274537785558783 0.4 left
BROKEN MARGIN!
convertViewVec: called in an invalid context
convertViewVec: called in an invalid context
0.2998929058033455 0.4 behind
BROKEN MARGIN!
convertViewVec: called in an invalid context
convertViewVec: called in an invalid context
0.03389183078307523 0.4 left
BROKEN MARGIN!
0.1257545572137938 0.4 right
BROKEN MARGIN!
0.20604094885490842 0.4 front
BROKEN MARGIN!
convertViewVec: called in an invalid context
0.11733480138553087 0.4 front
BROKEN MARGIN!
convertViewVec: called in an invalid context
convertViewVec: called in an invalid context
0.2261386110013388 0.4 left
BROKEN MARGIN!
convertViewVec: called in an invalid context
0.10859933790817577 0.4 right
BROKEN MARGIN!
0.17036471780332807 0.4 left
BROKEN MARGIN!
0.21985563128597363 0.4 right
BROKEN MARGIN!
0.2997315793366022 0.4 behind
BROKEN MARGIN!
0.08207759256993974 0.4 right
BROKEN MARGIN!
0.3923129559317601 0.4 front
BROKEN MARGIN!
0.013859992422528222 0.4 right
BROKEN MARGIN!
0.2703106931489372 0.4 right
BROKEN MARGIN!
0.05204691796960281 0.4 behind
BROKEN MARGIN!
0.04159258864015758 0.4 front
BROKEN MARGIN!
0.3932999393607828 0.4 front
BROKEN MARGIN!
convertViewVec: called in an invalid context
Fra:1 Mem:59.51M (0.00M, Peak 59.51M) | Time:00:00.00 | Preparing Scene data
Fra:1 Mem:79.70M (0.00M, Peak 80.68M) | Time:00:00.13 | Preparing Scene data
Fra:1 Mem:79.70M (0.00M, Peak 80.68M) | Time:00:00.13 | Creating Shadowbuffers
Fra:1 Mem:79.70M (0.00M, Peak 80.68M) | Time:00:00.14 | Raytree.. preparing
Fra:1 Mem:101.67M (0.00M, Peak 101.67M) | Time:00:00.18 | Raytree.. building
Fra:1 Mem:100.49M (0.00M, Peak 134.78M) | Time:00:00.99 | Raytree finished
Fra:1 Mem:100.49M (0.00M, Peak 134.78M) | Time:00:00.99 | Creating Environment maps
Fra:1 Mem:100.49M (0.00M, Peak 134.78M) | Time:00:00.99 | Caching Point Densities
Fra:1 Mem:100.49M (0.00M, Peak 134.78M) | Time:00:01.00 | Sce: Scene Ve:163332 Fa:159977 La:1
Fra:1 Mem:100.49M (0.00M, Peak 134.78M) | Time:00:01.00 | Loading voxel datasets
Fra:1 Mem:100.49M (0.00M, Peak 134.78M) | Time:00:01.00 | Sce: Scene Ve:163332 Fa:159977 La:1
Fra:1 Mem:100.49M (0.00M, Peak 134.78M) | Time:00:01.00 | Sce: Scene Ve:163332 Fa:159977 La:1
Fra:1 Mem:100.49M (0.00M, Peak 134.78M) | Time:00:01.00 | Volume preprocessing
Fra:1 Mem:100.49M (0.00M, Peak 134.78M) | Time:00:01.01 | Sce: Scene Ve:163332 Fa:159977 La:1
Fra:1 Mem:100.49M (0.00M, Peak 134.78M) | Time:00:01.01 | Sce: Scene Ve:163332 Fa:159977 La:1
Fra:1 Mem:102.66M (0.00M, Peak 134.78M) | Time:00:01.02 | Scene, Part 2-2
Fra:1 Mem:101.66M (0.00M, Peak 134.78M) | Time:00:01.06 | Scene, Part 1-2
Fra:1 Mem:58.51M (0.00M, Peak 134.78M) | Time:00:01.07 | Sce: Scene Ve:163332 Fa:159977 La:1
Saved: 'C:\Users\basit\AppData\Local\Temp\tmp0js12txa.png'
 Time: 00:01.19 (Saving: 00:00.11)

Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Koc\CLEVR_v1.0_no_images\clevr-dataset-gen\image_generation\render_images.py", line 568, in <module>
    main(args)
  File "C:\Koc\CLEVR_v1.0_no_images\clevr-dataset-gen\image_generation\render_images.py", line 187, in main
    output_blendfile=blend_path,
  File "C:\Koc\CLEVR_v1.0_no_images\clevr-dataset-gen\image_generation\render_images.py", line 310, in render_scene
    objects, blender_objects = add_random_objects(scene_struct, num_objects, args, camera)
  File "C:\Koc\CLEVR_v1.0_no_images\clevr-dataset-gen\image_generation\render_images.py", line 368, in add_random_objects
    return add_random_objects(scene_struct, num_objects, args, camera)
  File "C:\Koc\CLEVR_v1.0_no_images\clevr-dataset-gen\image_generation\render_images.py", line 368, in add_random_objects
    return add_random_objects(scene_struct, num_objects, args, camera)
  File "C:\Koc\CLEVR_v1.0_no_images\clevr-dataset-gen\image_generation\render_images.py", line 368, in add_random_objects
    return add_random_objects(scene_struct, num_objects, args, camera)
  File "C:\Koc\CLEVR_v1.0_no_images\clevr-dataset-gen\image_generation\render_images.py", line 436, in add_random_objects
    all_visible = check_visibility(blender_objects, args.min_pixels_per_object)
  File "C:\Koc\CLEVR_v1.0_no_images\clevr-dataset-gen\image_generation\render_images.py", line 492, in check_visibility
    os.remove(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\basit\\AppData\\Local\\Temp\\tmp0js12txa.png'

Blender quit

**Comment by daniel-scholz** [comment]
I had to call `os.close(f)`  before `os.remove(path)`.
